### ISSUE TITLE
Would  you consider refactoring this line so that the "text" string is not expanded inline inside the function call to output( ... text ...)

### ISSUE THREAD

**Issue by stephen-clark-mle** [opennars/OpenNARS-for-Applications#108]
https://github.com/opennars/OpenNARS-for-Applications/blob/e01d860dff2ac06e8d603ddedee0f717715103f2/english_to_narsese.py#L143

**Comment by stephen-clark-mle** [comment]
# build up sentence either a a set of strings or in another function.
# this would make debugging easier.
narsese_sentence =
 "<" 
+  subject_modifiers.replace("_subject_", subject) 
+ " --> (" 
+ prep 
+ " /1 " 
+ prep_object_modifiers.replace("_prep_object_", prep_object)
+ ")>" 
+ punctuation 

output(negated, narsese_sentence )

**Comment by patham9** [comment]
I fully agree, thank you! Previously it was just a Proof Of Concept, but now it's time to modularize the NLP channel's code and to document how it works properly. There are currently some weaknesses inbuilt which can easily be removed but will be easier to address after the refactoring.
Feel free to create a Pull Request, or else I will apply your change with the next refactoring of the file. It can take a few days as Christmas is on the way and I need to finish 2 reports before the end of 2020.

Also: I guess it will need a better POS tagger, and conditionals (if, then, leads to, ...) should be handled with the word types like CONJ (and, but, ...) rather than the recent hack which won't stay: "split apart sentence at conditional position, parse each side extra, fit results into implication".

**Comment by patham9** [comment]
this script has been re-implemented in a much more modular and flexible way, clearly separating output from syntactic transforms, which resolves this.
For reference, the old script can be found in https://github.com/patham9/NARSNLP (NLP_old.py) or in commit 4b7d53fb8a38a347c35777e909d6954a599de374
