### ISSUE TITLE
Compiling on BSD

### ISSUE THREAD

**Issue by djireland** [opennars/OpenNARS-for-Applications#118]
I couldn't compile on a BSD system (DragonFly BSD) because of: 

src/NetworkNAR/UDP.c:41:19: error: 'PF_INET' undeclared (first use in this function); did you mean 'AF_INET'?
     return socket(PF_INET, SOCK_DGRAM, 0);
                   ^~~~~~~
                   AF_INET

If you change 'PF_INET' to 'AF_INET' it compiles. 

In the Linux kernel these are the same anyway:

```C
/* Protocol families, same as address families. */
#define PF_INET     AF_INET
```

**Comment by patham9** [comment]
Hi!

Good catch! Usually I would expect PF_INET to exist in BSD headers, but I
think PF_INET and AF_INET are the same in 99% of implementations anyway so
maybe that's why they dropped it. I might change it to AF_INET as
practicality is more important than "looking conceptually right" when the
latter gives compilation errors. :)
Alternatively you can compile it this way without source change:
sh build.sh -DPF_INET=AF_INET

Best regards,
Patrick

**Comment by djireland** [comment]
Thanks.
