### ISSUE TITLE
Setting operation names for UDPNARS

### ISSUE THREAD

**Issue by ntoxeg** [opennars/OpenNARS-for-Applications#158]
I can’t seem to be able to perform `*setopname` properly when using UDPNARS. Even when sent immediately after starting it just complains that you can only do that at the beginning or after reset and shuts down. I also tried to send `*reset` just before `*setopname` but it still didn’t work. I've noticed that Python examples also don’t show sending such input, e. g the toothbrush example just skips those commands (does it even work when op names are not set?).

Is there a way for me to set operation names with UDPNARS and if so, what is it?

**Comment by patham9** [comment]
Hi! Thank you for raising this issue, the check was indeed too strict for the UDPNAR continuous operation mode. I added the check to make sure there would be no misuse of setopname after procedure knowledge with a previous op name was already given to the system or learned by the system.
Fixed with https://github.com/opennars/OpenNARS-for-Applications/commit/cddb4fabd8bf51e3ba130417619554f9907d8c01
