### ISSUE TITLE
bug: (.) is not parsed correctly

### ISSUE THREAD

**Issue by PtrMan** [opennars/OpenNARS-for-Applications#240]
<{(a . b)} --> exp>.
    Input: <{a b} --> exp>. Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000

expected behaviour: parsing it as `<{(a . b)} --> exp>.`

**Comment by patham9** [comment]
Oops this was my fault:
I told you to use
`<a --> (test . t)>.`
and
`<a --> (test . f)>.`
to avoid `<t <-> f>` to be derived.
But "." is already used as a set element copula to allow for multi-ary sets with the 2-ary set handling, which is why the above reduction happens.
If you want instances and properties with internal structures, just use the following instead, which doesn't demand a new copula:
`<a --> [(test * t)]>.`
`<a --> [(test * f)]>.`

**Comment by PtrMan** [comment]
hm or I will try using products for the representation

**Comment by patham9** [comment]
or simply: <a --> test_f>.
