### ISSUE TITLE
Can not find NAR shell 

### ISSUE THREAD

**Issue by zelin8** [opennars/OpenNARS-for-Applications#266]
I followed the instructions  and try to run NAR shell but it says: 

./NAR : The term './NAR' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At line:1 char:1
+ ./NAR shell
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (./NAR:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I 've ran the build.sh. Is there something I missed?

**Comment by ARCJ137442** [comment]
Maybe this happened in PowerShell on Windows?

Windows executables have a.exe extension, and ONA requires [cygwin](https://www.cygwin.com/) on Windows to compile.

If you have compiled successfully while running `build.sh`, you need to run `./NAR.exe shell` in PowerShell instead of `. /NAR shell`;
If any compilation errors occur while build.sh is running, also consider configuring [cygwin](https://www.cygwin.com/) for successful compilation.

**Comment by patham9** [comment]
Yes on windows it has to be `./NAR.exe` shell instead not `./NAR shell`. Cygwin will work, WSL too. Visual Studio stuff has own build scripts but its C99 compliance should be good enough in the meanwhile to compile&run the system but not using the provided build.sh
