### ISSUE TITLE
(Bug) Narsese Parsing: Can't Parse copula `|->` correctly

### ISSUE THREAD

**Issue by ARCJ137442** [opennars/OpenNARS-for-Applications#269]
## Background

I inputted a sample narsese input for testing:

```narsese
<<<a --> b> |-> c> <-> <<d =/> e> ==> <f <=> g>>>.
```

Expected ONA output is:

```plaintext
Input: <<<a --> b> |-> c> <-> <<d =/> e> ==> <f <=> g>>>. Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
```

But actually I got:

```plaintext
Input: ((<a --> b>| )c ). Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
```

which is confusing to me.

## Minimal Work Example

Input this into ONA:

```narsese
<a |-> b>.
```

will also trigger:

```plaintext
Input: (a| ). Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
```

which is more complicated than

```plaintext
Input: <a |-> b>. Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
```

## Some attempts to figure out this bug

I looked through the code for `Narsese.c`:

<https://github.com/opennars/OpenNARS-for-Applications/blob/cb0d36a01962781f90b4f92d08a9670b6f85682f/src/Narsese.c#L492-L505>

It seems that the `|->` named constant `HAS_CONTINUOUS_PROPERTY` is likely a type of statment copula.

Is there something wrong with my operation?

**Comment by patham9** [comment]
The officially supported grammar is listed here: https://github.com/opennars/OpenNARS-for-Applications/wiki/Narsese
**|->** was a recent addition which is only valid in statements of the form.
`<{instance} |-> [propertyName]>. :|: %v%`
This copula will likely be removed due to the new more complete value handling as demonstrated in
http://91.203.212.130/AniNAL/demo_complex_continuous_shades.html
and 
http://91.203.212.130/AniNAL/demo_complex_shades.html
which will be documented with the next release.

**Comment by ARCJ137442** [comment]
Ok, I see that.
Almost forgot that ONA also has a wiki, which I will read and refer to later.
