### ISSUE TITLE
motor babble prevents correct exec

### ISSUE THREAD

**Issue by PtrMan** [opennars/OpenNARS-for-Applications#52]
>*motorbabbling=true
>
><a --> A>. :|:
><(<a --> A> &/ ^left ) =/> <x --> Z> >.
>
><(<x --> Z> &/ ^pick ) =/> <{(make * icecreme)} --> cmd> >.
><{(make * icecreme)} --> cmd>! :|:
>20
><{(make * icecreme)} --> cmd>! :|:
>100

gives

Input: <a --> A>. :|: occurrenceTime=2 Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
Input: <(<a --> A> &/ ^left) =/> <x --> Z>>. Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
Input: <(<x --> Z> &/ ^pick) =/> <{(make * icecreme)} --> cmd>>. Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
Input: <{(make * icecreme)} --> cmd>! :|: occurrenceTime=6 Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
^go executed with args
Input: ^go. :|: occurrenceTime=6 Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
performing 20 inference steps:
done with 20 additional inference steps.
Input: <{(make * icecreme)} --> cmd>! :|: occurrenceTime=28 Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
Derived: <{(make * icecreme)} --> cmd>! :|: occurrenceTime=28 Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
Derived: <x --> Z>! :|: occurrenceTime=28 Priority=1.000000 Truth: frequency=1.000000, confidence=0.810000
Derived: <a --> A>! :|: occurrenceTime=28 Priority=1.000000 Truth: frequency=1.000000, confidence=0.729000
performing 100 inference steps:
done with 100 additional inference steps.
Statistics:
countConceptsMatchedTotal:      1
countConceptsMatchedMax:        1
countConceptsMatchedAverage:    0
currentTime:                    129
total concepts:                 4
Maximum chain length in concept hashtable = 1

while I expected that it calls left at some point, which is happening as expected when
>*motorbabbling=false
is done

**Comment by patham9** [comment]
This is expected behavior because currently motor babbling is triggered by existing goals, so only if you add them continuously you will see increasingly more babbling. Another option would be to to let it happen for instance with a fixed rate per inference steps, but then the babbling is cycle dependent rather than input goal rate dependent. Also it can lead to collisions with existing action choices as well, but this shouldn't be an issue. Not sure what the best babbling approach is yet, but this is not a bug.
